[workflow]
camera_root = "/Users/christopherstorer/working/camera"

[memory_card_copy]
card_mount_root = "/Volumes"
low_disk_warning_gb = 30.0
low_disk_warning_percent = 5.0
copy_verification = "basic"
halt_on_insufficient_space = true
capture_date_source = "filesystem"
# TODO: perhaps it makes more sense to list the extensions we DO want to copy, rather than the ones we want to ignore?
ignored_extensions = [".ctg", ".log", ".tmp", ".fir", ".to3"]

[video_notes]
max_duration_seconds = 15.0
transcription_model = "mlx-community/whisper-medium-mlx"
